variables:
  TEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/ci:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
  VERSION_IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG
  # Docker in Docker
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - test
  - release

build-docker:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$TEST_IMAGE" .
    - docker push "$TEST_IMAGE"
  tags:
    - docker

release-docker:
  stage: release
  dependencies:
    - build-docker
  when: manual
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$TEST_IMAGE"
    - docker tag "$TEST_IMAGE" "$VERSION_IMAGE"
    - docker tag "$VERSION_IMAGE" "$RELEASE_IMAGE"
    - docker push "$VERSION_IMAGE"
    - docker push "$RELEASE_IMAGE"
  only:
    - tags
  tags:
    - docker
